#!/usr/bin/env bash
# Install Nginx and configure it to listen on port 80
# Print "Hello World"

# Update package lists
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Print "Hello World!" to the default Nginx index file
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Start Nginx service
sudo service nginx start

